// Layout of Contract:
// version
// imports
// errors
// interfaces, libraries, contracts
// Type declarations
// State variables
// Events
// Modifiers
// Functions

// Layout of Functions:
// constructor
// receive function (if exists)
// fallback function (if exists)
// external
// public
// internal
// private
// view & pure functions
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {VRFConsumerBaseV2Plus} from "@chainlink/contracts/src/v0.8/vrf/dev/VRFConsumerBaseV2Plus.sol";
import {VRFV2PlusClient} from "@chainlink/contracts/src/v0.8/vrf/dev/libraries/VRFV2PlusClient.sol";

/**
 * @title Raffle Contract
 * @author Sai Likhith SLD
 * @notice This contract is for creating a decentralized raffle system where users can participate by paying an entry fee.
 * The winner will be selected randomly using Chainlink VRF (Verifiable Random Function) to ensure fairness and transparency in the selection process.
 * @dev Implemnts ChainlinkVRF
 */
contract Raffle is VRFConsumerBaseV2Plus {
    /*error*/
    error Raffle__NotEnoughETHEntered();
    error Raffle__TransferFailed();
    error Raffle__RaffleNotOpen();
    error Raffle_UpKeepNotNeeded(uint256 currentBalance, uint256 numPlayers, uint256 raffleState);
    /*Type declarations*/
    enum RaffleState {
        OPEN, //0
        CALCULATING //1
    }

    /*State Variables*/
    uint256 private immutable i_entryFee;
    uint256 private immutable i_subscriptionId;
    bytes32 private immutable i_keyHash;
    uint32 private immutable i_callbackGasLimit;
    uint16 private constant REQUEST_CONFIRMATIONS = 3;
    uint32 private numWords = 1;
    address payable[] private s_players;
    uint256 private s_lastTimeStamp;
    uint256 private i_interval;
    bool private enableNativePayment = false;
    address private s_recentWinner;
    RaffleState private s_raffleState;
    /*events*/
    event RaffleEnter(address indexed player);
    event WinnerPicked(address indexed winner);
    event RequestedRaffleWinner(uint256 indexed requestId);

    constructor(
        uint256 entryFee,
        uint256 interval,
        address _vrfCoordinator,
        uint256 subscriptionId,
        bytes32 _keyHash,
        uint32 _callbackGasLimit
    ) VRFConsumerBaseV2Plus(_vrfCoordinator) {
        i_entryFee = entryFee;
        i_interval = interval;
        i_subscriptionId = subscriptionId;
        i_keyHash = _keyHash;
        i_callbackGasLimit = _callbackGasLimit;
        s_raffleState = RaffleState.OPEN;
        s_lastTimeStamp = block.timestamp;
    }

    function enterRaffle() external payable {
        // Function to allow users to enter the raffle by paying an entry fee
        //require(msg.value >= i_entryFee, "Not enough ETH entered");
        //require(msg.value >= i_entryFee, Raffle__NotEnoughETHEntered());
        if (s_raffleState != RaffleState.OPEN) {
            revert Raffle__RaffleNotOpen();
        }
        if (msg.value < i_entryFee) {
            revert Raffle__NotEnoughETHEntered();
        }
        s_players.push(payable(msg.sender));
        emit RaffleEnter(msg.sender);
    }

    function checkUpKeep() public view returns (bool upKeepNeeded) {
        bool timehaspassed = (block.timestamp - s_lastTimeStamp) >= i_interval;
        bool hasplayers = s_players.length > 0;
        bool isopen = s_raffleState == RaffleState.OPEN;
        bool haseth = address(this).balance > 0;
        upKeepNeeded = (timehaspassed && hasplayers && isopen && haseth);
        return upKeepNeeded;
    }

    function pickWinner() external {
        //perform upkeep to pick a winner
        // Function to pick a winner randomly using Chainlink VRF
        bool upKeepNeeded = checkUpKeep();
        if (!upKeepNeeded) {
            revert Raffle_UpKeepNotNeeded(address(this).balance, s_players.length, uint256(s_raffleState));
        }
        s_raffleState = RaffleState.CALCULATING;
        //getting a random number is two step process
        //1. request a random number from chainlink vrf coordinator
        //2. once the random number is generated by the coordinator, it will call
        //the fulfillRandomWords function in our contract with the random number as an argument

        VRFV2PlusClient.RandomWordsRequest memory request = VRFV2PlusClient.RandomWordsRequest({
            keyHash: i_keyHash,
            subId: i_subscriptionId,
            requestConfirmations: REQUEST_CONFIRMATIONS,
            callbackGasLimit: i_callbackGasLimit,
            numWords: numWords,
            extraArgs: VRFV2PlusClient._argsToBytes(VRFV2PlusClient.ExtraArgsV1({nativePayment: enableNativePayment}))
        });
        uint256 requestId = s_vrfCoordinator.requestRandomWords(request);
        emit RequestedRaffleWinner(requestId);
    }

    //CEI checks, effects, interactions pattern
    function fulfillRandomWords(uint256 requestId, uint256[] calldata randomWords) internal override {
        //checks
        //internal contract state changes
        uint256 indexofwinner = randomWords[0] % s_players.length;
        address payable winner = s_players[indexofwinner];
        s_recentWinner = winner;
        s_raffleState = RaffleState.OPEN;
        s_players = new address payable[](0);
        s_lastTimeStamp = block.timestamp;
        emit WinnerPicked(winner);
        //Interactions(external calls)
        (bool success,) = winner.call{value: address(this).balance}("");
        if (!success) {
            revert Raffle__TransferFailed();
        }
    }

    /*
     * Getter Functions
     */
    function getEntryFee() external view returns (uint256) {
        return i_entryFee;
    }

    function getRaffleState() external view returns (RaffleState) {
        return s_raffleState;
    }

    function getplayers(uint256 index) external view returns (address) {
        return s_players[index];
    }

    function getRecentWinner() external view returns (address) {
        return s_recentWinner;
    }

    function getlastTimeStamp() external view returns (uint256) {
        return s_lastTimeStamp;
    }
}
